lucidrains/x-transformers

README.md

Encoder/Decoder Example is not working. The Encoder requires a value for `enc_num_memory_tokens`.
This should fix it.

Fixed ReadMe Encoder/Decoder Example

---

x_transformers/x_transformers.py

This bug is fixed based on a similar implementation from huggingface's transformers: (https://github.com/huggingface/transformers/blob/d944966b19a4d6860bddc7cdc1ba928ca8a0da91/src/transformers/models/t5/modeling_t5.py#L363)

bug fix for _relative_position_bucket

---

x_transformers/autoregressive_wrapper.py

`AutoregressiveWrapper.forward` has some logic for replacing a mask. But if `mask` was already the right shape, it gets dropped from `kwargs`.
This PR is an attempt to guess what was intended. I haven't yet convinced myself that the "auto-solve" logic is always what is desired; "explicit is better than implicit" would suggest removing it in favor of an assert with a helpful message (or an exception).
I also removed `pad`, which seemed to be unused (why not use it?).
This is a drive-by PR; I have not tested this code.

Fix potential dropped mask in AutoregressiveWrapper

---

x_transformers/x_transformers.py

currently one has to call the `generate` method on decoder directly to change its arguments. This change enable passing  arguments on main model's `generate` method itself.

added support to pass kwargs to decoder generate method

---

x_transformers/x_transformers.py

Currently when using rotary embedding, models becomes unpickleable and I get this error when trying to pickle 
`AttributeError: Can't pickle local object 'always.<locals>.inner'`
This PR fixes this issue

make models pickleable

---

x_transformers/x_transformers.py

Hi!
I experienced some problems during backward pass when tried to stack transformers on top of LSTM if there were inplace operations in transformers. So I decided to replace them with not inplace versions. It helped in my case, maybe worth including in the main repo.
```python
import torch
from torch import nn
from x_transformers import ContinuousTransformerWrapper, Encoder
class Model(nn.Module):
def __init__(self, ):
super().__init__()
self.rnn = nn.LSTM(input_size=64, hidden_size=64, num_layers=1,
bidirectional=False, batch_first=True)
self.transformer = ContinuousTransformerWrapper(
max_seq_len=100,
attn_layers=Encoder(
dim=64,
depth=1,
heads=4
)
)
def forward(self, x):
x, _ = self.rnn(x)
x = self.transformer(x)
return x
m = Model().cuda()
x = torch.randn((10, 20, 64)).cuda()
loss = …
```

eliminate inplace operations

---

x_transformers/x_transformers.py

Missed this part earlier, as it's default on currently :)

avoid saving intermediaries unless needed

---

x_transformers/x_transformers.py

This PR enables feeding an arbitrary position tensor to `AbsolutePositionalEmbedding` and `FixedPositionalEmbedding`, including:
- A different sequence of positions for each item in the batch
- Float (non-integer) positions in the case of `FixedPositionalEmbedding`

Arbitrary positions in absolute PE

---

x_transformers/x_transformers.py

After rearranging the shapes in https://github.com/lucidrains/x-transformers/commit/73a99f3d85a9b93cea6e09c721b66d555695d0cd, the number of unalibied heads was computed incorrectly and models with `AliBi` failed with `RuntimeError`.

Fix bug with bias and slopes padding in ALiBi

---

x_transformers/x_transformers.py

In current shift implementation this will fail
```python
t = torch.rand((2,1,10))
shift(t, 2)
```
with following exception
```python
File /cluster/work/gurvinde/.env/lib/python3.9/site-packages/torch/nn/functional.py:4364, in _pad(input, pad, mode, value)
4362 assert len(pad) // 2 <= input.dim(), "Padding length too large"
4363 if mode == "constant":
-> 4364     return _VF.constant_pad_nd(input, pad, value)
4365 else:
4366     assert value == 0.0, 'Padding mode "{}"" doesn\'t take in value argument'.format(mode)
RuntimeError: start (0) + length (-1) exceeds dimension size (1).
```
This patch fixes the issue.

amount by which to shift should be less than or equal to input tensor dimension

---

x_transformers/x_transformers.py

In Transformer-XL the length of key sequence `j` is larger than that of query `i` due to memory. i.e., ```j = len(mem) + i```
the keys in mem are past keys so the positional biases have to be shifted by ```len(mem) = j - i```
This is correctly implemented in the causal lookahead mask.

Fix wrong positional biases

---

x_transformers/x_transformers.py

When `j > i` (0, 0) is not the current time position. For example,
```
> bias
tensor([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
[-6, -5, -4, -3, -2, -1,  0,  1,  2,  3],
[-7, -6, -5, -4, -3, -2, -1,  0,  1,  2],
[-8, -7, -6, -5, -4, -3, -2, -1,  0,  1],
[-9, -8, -7, -6, -5, -4, -3, -2, -1,  0]])
```
so if you crop from (0, 0) as:
```
> bias[:2,:3] 
tensor([[-5, -4, -3],
[-6, -5, -4]])
```
but this is wrong, and it should be
```
> bias[-2:,-3:] 
tensor([[-1,  0,  1],
[-2, -1,  0]])
```

Fix wrong submatrix indexing

---

x_transformers/x_transformers.py

This PR allows a user to specify the `scaled_sinu_pos_emb` option for either a decoder or encoder when using the XTransformers interface: `dec_scaled_sinu_pos_emb = True` and/or `enc_scaled_sinu_pos_emb = True`
. Previously it defaulted to only use absolute embeddings regardless of how you specified this option

Allow specifying scaled_sinu_pos_emb using XTransformers Interface

---

x_transformers/attend.py

When calling torch.save on the model, since implementing the fast attention, i got a pickling error:
```
----> 1 torch.save(x, 'test.pt')
File /usr/local/Caskroom/miniconda/base/envs/repo/lib/python3.8/site-packages/torch/serialization.py:441, in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
439 if _use_new_zipfile_serialization:
440     with _open_zipfile_writer(f) as opened_zipfile:
--> 441         _save(obj, opened_zipfile, pickle_module, pickle_protocol)
442         return
443 else:
File /usr/local/Caskroom/miniconda/base/envs/repo/lib/python3.8/site-packages/torch/serialization.py:653, in _save(obj, zip_file, pickle_module, pickle_protocol)
651 pickler = pickle_module.Pickler(data_buf, protocol=pickle_protocol)
652 pickler.persistent_id = persistent_id …
```

Could not call torch.save on the model

---

x_transformers/x_transformers.py

Hello, 
The tie embedding throws an error since `token_emb` isn't directly an `nn.Embedding` instance but of the custom `TokenEmbedding` class.
A small PR to fix that

Fix weight tying bug

---

x_transformers/continuous.py

hit these trying to use memory tokens with the continuous wrapper

fix missed imports in continuous.py

---

x_transformers/x_transformers.py

TransformerWrapper takes an optional keyword argument token_emb. If not specified or set to the default value None, a new TokenEmbedding is created exactly as before.
If a TokenEmbedding is specified, it is used as the token_emb.
This feature is useful for parameter sharing, allowing the use of a single shared embedding with multiple Transformers. I have a use case for this feature in modular multilingual machine translation.
Closes #266

Allow passing in a pre-existing TokenEmbedding into TransformerWrapper

---

x_transformers/xval.py

Fixes `NameError: name 'always' is not defined` when instantiating `XValTransformerWrapper`

Missing always definition in XVal

---

tests/test_x_transformers.py
x_transformers/x_transformers.py

Latent Transformer models use multiple CLS tokens to reduce variable length sequences into fixed size latent vectors using multiple dummy/CLS tokens. This PR adds an argument `num_cls_tokens` to `TransformerWrapper` to support such architectures.
Examples of publications using this approach:
- https://arxiv.org/abs/2207.04632
- https://proceedings.neurips.cc/paper_files/paper/2023/file/fdba5e0a9b57fce03e89cc0cad0a24e9-Paper-Conference.pdf

Support multiple CLS tokens

---

tests/test_x_transformers.py
x_transformers/x_transformers.py

Hi @lucidrains, I use x-transformers extensively and often run into the need to use custom embedder and logit mapper classes together with the `AutoregressiveWrapper` class, for e.g., to implement pointer networks (https://arxiv.org/abs/1506.03134). Currently this is not possible, so I work with the lower level `Decoder` class and implement the wrapper myself.
In this PR, I tried to enable support for this by slightly reorganizing the `TokenEmbedding` class, and adding a class called `LogitMapper` to be used as the `TransformerWrapper.to_logits` layer. The idea is that we can implement custom classes conforming to these interfaces and everything should work seamlessly. These classes accept kwargs in their forward method that allows us to pass additional tensors to them.
The unit tests all …

Customizable Embedder and Logit Mapper

---

setup.py

The pypa `packaging` module is a required import-time requirement (eg; [here](https://github.com/lucidrains/x-transformers/blob/abeedc8cb60180892f1c19b42548c9833abe4f5b/x_transformers/x_transformers.py#L6)) but isn't listed in setup.py. Adding it here for completeness.

Add `packaging` as requirement
